#!/usr/bin/env php
<?php
/**
 * Germ: A command line tool for Germ!
 *
 * @author Jeremy Ward <jeremy@jmichaelward.com>
 * @package JMW\Germ
 */

namespace JMW\Germ;

use Symfony\Component\Console\Application;

$local_dir = __DIR__ . '/vendor/autoload.php';
$autoload = is_readable( $local_dir ) ? $local_dir : dirname(__FILE__, 4) . '/vendor/autoload.php';

if (!is_readable($autoload)) {
    echo "Could not find autoloader. Germ out.\n";
    return;
}

require_once $autoload;

$app = new Application('germ', '1.0.0');

(new Germ($app))->registerCommands();

$app->run();
